### ISSUE TITLE
gpt example error

### ISSUE THREAD

**Issue by WooilJeong** [pynecone-io/pynecone-examples#21]
![image](https://user-images.githubusercontent.com/38076110/212634016-10615712-a8ca-42b3-91bc-c301912c623e.png)

hello. I keep getting the following error while running the example code. This is the result of pc init and pc run in the gpt example folder after git clone. What could be the problem?

**Comment by Alek99** [comment]
Try this with the new release should be fixed

**Comment by Alek99** [comment]
Nice marking al closed
