### ISSUE TITLE
Several Issues with Twitter demo

### ISSUE THREAD

**Issue by HighnessAtharva** [pynecone-io/pynecone-examples#23]
## Able to login with empty input fields
With reference to this [demo](https://twitter.pynecone.app/signup) I am able to login without entering any email or password and when I try to sign up without any email or password, I get the message "username already exists". 

This could be an issue where any checks were not placed in the `signup` function allowing empty values "" for username and password to be entered in the database. Please see if you can fix this and maybe even add a warning in the docs to alert the users about this potential pitfall.

## Passwords do not match error (possibly due to space but could be handled better)
![password allows space and alerts different error](https://user-images.githubusercontent.com/68660002/213985268-4d029e01-8e13-4bbb-8bed-367d98e4448d.png)

## As following list grows, the tweet button disappears. Need another scrollbar here.
![tweet button disappears](https://user-images.githubusercontent.com/68660002/213985318-2d3310d1-6d52-4b64-a80c-20f0ef2bf92c.png)

## Scrolling to the bottom of the page shows weird scrollbars
![weird scrollbars](https://user-images.githubusercontent.com/68660002/213985303-dbcdac4c-2e95-4505-a19c-d23d3e6c2dff.png)

**Comment by Alek99** [comment]
Thanks for pointing this out. Got it I can get to this later this week, feel free to submit a pr to fix these issues too if your up for it. Otherwise Ill do it sometime this week

**Comment by milochen0418** [comment]
@HighnessAtharva  @Alek99 
Do you think we should close this issue?
Because we have a new Twitter example now. 
- https://github.com/pynecone-io/pynecone-examples/pull/89
