### ISSUE TITLE
Mac OS X pynecone==0.1.27 /bin/bash: next: command not found

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#56]
Before, My development environment is running well with pyhteonce 0.1.24
Today I try to upgrade pynecone into 0.1.27 for testing every examples on pynecone-examples.

pynecone==0.1.24 
I can run example from this project. 

In the next released on the PiPy 
repynecone==0.1.27

I use the same node environment to test on my computer. 
pynecone==0.1.24 is working but not pynecone==0.1.27

My node version : v16.10.0   
My testing way is to use the same nodejs environment to test pc 0.1.24 and pc 0.1.27. 

There is the following error on pynecone==0.1.27
```
───────────────────────────────────────────────────── Installing frontend packages ─────────────────────────────────────────────────────
bun install v0.5.5 (242dcea2)
───────────────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────────────
$ next dev
/bin/bash: next: command not found
error: script "dev" exited with code 127
```

**Comment by milochen0418** [comment]
Testing on my mac 

clean environment to pip install pynecone 0.1.27 
create empty project and run it with my current node environment 
pc init 
```pcconfig.py
import pynecone as pc

class ExamplepcpipConfig(pc.Config):
    pass

config = ExamplepcpipConfig(
    app_name="example_pcpip127",
    db_url="sqlite:///pynecone.db",
    env=pc.Env.DEV,
)
```
pc run 
```
$ next dev
/bin/bash: next: command not found
error: script "dev" exited with code 127
```

same issue here after doing this steps.

**Comment by milochen0418** [comment]
Bun installation issue. 

In the mac os X, 
the downloaded bun will install in ~/.bun/bin/bun 
If the file is there, then bun installation support by the current code cannot overwrite it. 
But if we delete ~/.bun/bin/bun , then we can run the current code and ~/.bun/bin/bun will become new file.

**Comment by milochen0418** [comment]
After killing ~/.bun/bin/bun file manually, and do `pc init` and `pc run`. 
We can see that new bun can be download by pc init 
and pc run will run on bun v0.5.9. 

So the root cause of this issue is because bun file cannot be replace by current installation bash script.

**Comment by Alek99** [comment]
We may need to do -f and ask for a permission with y/n command 

`curl -fsSL https://bun.sh/install | bash -s -- -f bun-v0.5.9`

**Comment by milochen0418** [comment]
> curl -fsSL https://bun.sh/install | bash -s -- -f bun-v0.5.9
In my Mac computer, 
I can use `curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.9` (without -f)

But when I use `curl -fsSL https://bun.sh/install | bash -s -- -f bun-v0.5.9`, it is failed.
And the following is the error message
error: Failed to download bun from "https://github.com/oven-sh/bun/releases/download/-f/bun-darwin-x64.zip"

**Comment by milochen0418** [comment]
This issue is because of bun version cannot match to pynecone version. 
But int the next release  pynecone==0.1.29, this issue will not be exists because the following 
- https://github.com/pynecone-io/pynecone/pull/938

**Comment by milochen0418** [comment]
Testing this issue in the current pc 0.1.33 again. 
I ensure this issue is solved
<img width="1155" alt="Screenshot 2023-06-11 at 11 32 02 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/dcd060d1-eff3-4e7e-8fe7-7b1d986afb3c">
