### ISSUE TITLE
pc init issue on nba example: pc  init cannot afford to run well in the first time

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#63]
My environment
```
python 3.11.3 
pc 0.1.28
bun 5.9
Mac 13.3.1 (Intel CPU)
```

The following step allows the developer to clean and re-init pc project.  
so it can simulate the situation of the first time to run the project
```
rm -rf .web && for i in $(find ./ | grep __pycache__$); do rm -rf $i; done && pc init &&  pc run
```

**TEST FAILED**: When you test it, open localhost:3000 cannot see anything. 

But if you change to use the following steps, the init procedure will work well for first time to run nba example.
```
rm -rf .web && for i in $(find ./ | grep __pycache__$); do rm -rf $i; done && pc init && ~/.bun/bin/bun install --cwd .web/ &&  pc run
```

I just add `~/.bun/bin/bun install --cwd .web/` after pc init. 
Then nba example can work in the first time.

I got this idea from @r0b2g1t 's contribution on PR 
- https://github.com/pynecone-io/pynecone/pull/911
- https://github.com/pynecone-io/pynecone/pull/911/files

**Comment by r0b2g1t** [comment]
```pc init``` only initialize the Pynecone project. Without installing any bun package. The ```pc run``` command installs packages. If you try to run your project in the container example it is necessary to run the command ```/app/.bun/bin/bun install --cwd .web/``` which installs the bun packages during the image build and have them right in place when you run your container.

**Comment by milochen0418** [comment]
> `pc init` only initialize the Pynecone project. Without installing any bun package. The `pc run` command installs packages. If you try to run your project in the container example it is necessary to run the command `/app/.bun/bin/bun install --cwd .web/` which installs the bun packages during the image build and have them right in place when you run your container.

Thanks for replying. 
I don't run it in docker. 
I only run it in virtual env from my Mac computer.

**Comment by milochen0418** [comment]
@r0b2g1t 
Sorry ~ It's my fault. 
The version of node is 12.22.12 when I find out this issue. 
I forge to check node's version. 

So 12.22.12 have this issue. but when we use node 16.6.0 , there is no this issue.
