### ISSUE TITLE
clock example: cannot show default time zone on pc.select (0.1.32)

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#80]
```
My Testing Environment
        OS Darwin 22.4.0
        Pynecone 0.1.32
        Python 3.11.3
        Node v16.8.0
        Bun 0.5.9
```
clock example: cannot show default time zone on pc.select (0.1.32)
<img width="605" alt="Screenshot 2023-05-29 at 12 26 21 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/866fa1bc-4525-4a2b-98c6-4328505f7a88">

**Comment by milochen0418** [comment]
Set value attribute in pc.select may solve this issue.

**Comment by picklelo** [comment]
This should be working in the latest alpha - let me know if you're still seeing this.

**Comment by milochen0418** [comment]
> This should be working in the latest alpha - let me know if you're still seeing this.

In the 0.1.33 testing, we can see the following
<img width="821" alt="Screenshot 2023-06-11 at 11 42 07 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/88482496-0bc5-41c1-9db8-7ccf673367c1">

It doesn't show the time zone now. 


If we don't turn on the switch, then change the item in pc.select cannot change the clock picture too. 
<img width="639" alt="Screenshot 2023-06-11 at 11 42 15 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/c480845d-2d19-42c4-9f74-899148358e27">

<img width="683" alt="Screenshot 2023-06-11 at 11 42 21 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/aa00a87f-7a2f-45dc-bb4c-2b150ac3776d">

**Comment by milochen0418** [comment]
The issue reported from the above message is solved by the following PR and commit
- https://github.com/pynecone-io/pynecone-examples/pull/98
- https://github.com/pynecone-io/pynecone-examples/pull/103/commits/53faf1918741ad99b8184117798d9e5c47b4ac4c
