### ISSUE TITLE
clock example: switch ui is not correct after refresh (0.1.32)

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#81]
```
My Testing Environment
        OS Darwin 22.4.0
        Pynecone 0.1.32
        Python 3.11.3
        Node v16.8.0
        Bun 0.5.9
```
Turn switch on and refresh page. 
The switch is still on but clock is not moving. 
The expected switch on UI is to display switch-off 

<img width="605" alt="Screenshot 2023-05-29 at 12 26 21 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/7783af52-4a79-4a02-ab10-7ebc8cb7c728">

**Comment by picklelo** [comment]
This is because the event queue gets cleared when the page refreshes... I think we need to use some sort of localStorage potentially to save the event queue if we want to preserve it between refreshes. For now I added an on_load event to always turn the switch off on refreshes.

**Comment by milochen0418** [comment]
Note: This issue is solved by the following 
- https://github.com/pynecone-io/pynecone-examples/pull/98
