### ISSUE TITLE
upload example: failed to upload file sometimes (0.1.32)

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#88]
Click upload and no file update sometimes.

The content of TextArea shows the file's name in  .web/public/files/. 
The files are there, and GUI shows correctly. 
But just no thing uploads after selecting one file and uploading it.

pc 0.1.31 have the same bug too.

**Comment by milochen0418** [comment]
The root cause of this issue is 
- https://github.com/pynecone-io/pynecone/issues/1152

**Comment by picklelo** [comment]
Great catch! I put up a PR to fix this case

**Comment by milochen0418** [comment]
Issue solved by 
https://github.com/pynecone-io/pynecone/issues/1152
